In [12]:
import numpy as np

stuff = np.array([[[1,2,3,4,5,6,7],[1,2,3,4,5,6,7]]])
empty = np.zeros((1,2,7))
full = np.append(empty,stuff)

empty = np.concatenate((empty, stuff),axis=0)
print(empty)
new = np.delete(empty,0,0)
print(new)


[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[1. 2. 3. 4. 5. 6. 7.]
  [1. 2. 3. 4. 5. 6. 7.]]]
[[[1. 2. 3. 4. 5. 6. 7.]
  [1. 2. 3. 4. 5. 6. 7.]]]
